# Generated by Django 6.0.3 on 2026-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Posto Sem Nome', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('consumo', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
