# Generated by Django 6.0.3 on 2026-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='valor',
            new_name='preco_kwh',
        ),
        migrations.AddField(
            model_name='ponto',
            name='preco_ociosidade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ponto',
            name='preco_start',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ponto',
            name='tipos_carregador',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
