# Generated by Django 6.0.3 on 2026-03-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tipo1', 'Tipo 1 (J1772)'), ('tipo2', 'Tipo 2 (Mennekes)'), ('ccs1', 'CCS Combo 1'), ('ccs2', 'CCS Combo 2'), ('chademo', 'CHAdeMO'), ('gbdc', 'GB/T DC'), ('tesla', 'Tesla (NACS)'), ('schuko', 'Schuko (doméstico)')], max_length=20)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('inativo', 'Inativo / Manutenção')], default='livre', max_length=10)),
                ('potencia', models.FloatField(default=0, help_text='Potência individual deste conector (kW)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conectores', to='accounts.ponto')),
            ],
            options={
                'ordering': ['tipo', 'id'],
            },
        ),
    ]
