# Generated by Django 6.0.3 on 2026-04-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useronboarding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOnboarding',
        ),
    ]
