# Generated by Django 6.0.3 on 2026-04-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_useronboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='horario_abertura',
            field=models.TimeField(default='08:00', help_text='Horário de abertura (HH:MM)'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='horario_fechamento',
            field=models.TimeField(default='20:00', help_text='Horário de fechamento (HH:MM)'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(help_text='Data e hora do início da recarga agendada')),
                ('tempo_estimado', models.IntegerField(default=60, help_text='Tempo estimado em minutos')),
                ('energia_solicitada', models.FloatField(help_text='Energia solicitada em kWh')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('valor_estimado', models.FloatField(blank=True, help_text='Valor estimado em R$', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.conector')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='accounts.ponto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
